version: '3'

services:
  app:
    build: .
    container_name: dart-cams-app
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dart-cams.rule=Host(`cams.ingomc.de`)"
      - "traefik.http.routers.dart-cams.entrypoints=websecure"
      - "traefik.http.routers.dart-cams.tls=true"
      - "traefik.http.routers.dart-cams.tls.certresolver=letsencrypt" # Oder 'myresolver', je nach Traefik Config auf dem Server
      - "traefik.http.services.dart-cams.loadbalancer.server.port=80"
    networks:
      - traefik-public # WICHTIG: Das muss das Netzwerk sein, in dem dein Traefik l√§uft

networks:
  traefik-public:
    external: true
